code quality:
  stage: build
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - black .
    - mypy --ignore-missing-imports --exclude venv .
    - isort .
    - radon cc --ignore venv,tests .

test execution:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - pytest --cov

build and publish:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ilsaffff/ci-cd:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push ilsaffff/ci-cd:latest
