push to github:
  stage: build
  image:
    name: alpine/git:latest
    entrypoint: [""]
  only:
    - main
    - release
  script:
    - git clone --mirror https://Ilsaf:glpat-m1yiTFj7wsyy--GobGXW@appliedmath.gitlab.yandexcloud.net/computemath/cicd_python_cnn.git
    - git remote set-url --push origin https://Ilsaffff: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@github.com/Ilsaffff/test-release-.git
    - git fetch origin
    - git checkout origin/master # Переключаемся на ветку origin/master
    - git checkout -b squash_branch # Создаем новую ветку на основе origin/master
    - git reset --soft HEAD~1 # Squash всех коммитов, начиная с предыдущего коммита (не включительно)
    - git commit -m "Squashed and transferred all changes" # Коммит со всеми изменениями объединенными в один
    - git push -u origin squash_branch # Загружаем изменения в GitHub
  



code quality:
  stage: build
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run black --check .
    - poetry run isort --check-only .
    - poetry run mypy --ignore-missing-imports --exclude venv .
    - poetry run radon cc --ignore venv,tests .

test execution:
  stage: test
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run pytest --cov

build and publish to docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ilsaffff/ci-cd:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push ilsaffff/ci-cd:latest


