push to github:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run --rm -v "$PWD":/git -w /git alpine/git clone git@appliedmath.gitlab.yandexcloud.net:computemath/cicd_python_cnn.git
    - cd ci-cd
    - docker run --rm -v "$PWD":/git -w /git alpine/git push --mirror git@github.com:Ilsaffff/test-release-.git

code quality:
  stage: build
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run black --check .
    - poetry run isort --check-only .
    - poetry run mypy --ignore-missing-imports --exclude venv .
    - poetry run radon cc --ignore venv,tests .

test execution:
  stage: test
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run pytest --cov

build and publish to docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ilsaffff/ci-cd:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push ilsaffff/ci-cd:latest


