push to github:
  stage: build
  image: alpine/git:latest
  script:
    - git config user.email $GIT_EMAIL
    - git config user.name $GIT_NAME
    - git remote add gitlab_origin https://oauth2:$GITHUB_TOKEN@$GITHUB_REPO
    - git add .
    - git commit -m "init"
    - git push gitlab_origin HEAD:main -o ci.skip


code quality:
  stage: build
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run black --check .
    - poetry run isort --check-only .
    - poetry run mypy --ignore-missing-imports --exclude venv .
    - poetry run radon cc --ignore venv,tests .

test execution:
  stage: test
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run pytest --cov

build and publish to docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ilsaffff/ci-cd:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push ilsaffff/ci-cd:latest


