stages:
  - build
  - validate
  - test
  - deploy
  - release

build:
  stage: build
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
  script:
    - poetry install --no-root
  cache:
    paths:
      - .cache/
      - .venv/
    policy: push

validate:
  stage: validate
  image: python:3.10
  script:
    - poetry run black --check .
    - poetry run isort --check-only .
    - poetry run mypy --ignore-missing-imports --exclude venv .
    - poetry run radon cc --ignore venv,tests .
  cache:
    paths:
      - .cache/
      - .venv/
    policy: pull

test:
  stage: test
  image: python:3.10
  script:
    - poetry run pytest --cov --cov-fail-under=$PERCENT_COVERAGE
  cache:
    paths:
      - .cache/
      - .venv/
    policy: pull


push to docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ilsaffff/ci-cd:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push ilsaffff/ci-cd:latest


push to github:
  stage: release
  image:
    name: alpine/git:latest
    entrypoint: [""]
  only:
    - main
    - release
  script:
    - git clone --mirror $GITLAB_OAUTH_URL
    - git remote set-url --push origin $GITHUB_OAUTH_URL
    - git push -f origin main
