stages:
  - squashing
  - build
  - test
  - deploy


push to github:
  stage: squashing
  image:
    name: alpine/git:latest
    entrypoint: [""]
  only:
    - main
    - release
  script:
    - git clone --mirror https://Ilsaf:glpat-m1yiTFj7wsyy--GobGXW@appliedmath.gitlab.yandexcloud.net/computemath/cicd_python_cnn.git
    - git remote set-url --push origin https://Ilsaffff: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@github.com/Ilsaffff/test-squash.git
    - git fetch origin
    - git clean -fd
    - git checkout squash_branch
    - COMMIT_COUNT=$(git rev-list --count HEAD)
    - git rebase -i --root HEAD~$COMMIT_COUNT
    - git commit -m "Squashed and transferred all changes" # Коммит со всеми изменениями объединенными в один
    - git push -f origin squash_branch # Загружаем изменения в GitHub
  



code quality:
  stage: build
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run black --check .
    - poetry run isort --check-only .
    - poetry run mypy --ignore-missing-imports --exclude venv .
    - poetry run radon cc --ignore venv,tests .

test execution:
  stage: test
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run pytest --cov

build and publish to docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ilsaffff/ci-cd:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push ilsaffff/ci-cd:latest


