formatting:
  stage: build
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - black .
    - mypy --ignore-missing-imports --exclude venv .
    - isort .
    - radon cc --ignore venv,tests .

testing:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - pytest

build-and-publish:
  stage: deploy
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://127.0.0.1:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t ilsaffff/ci-cd:latest .
    - docker login -u ilsaffff -p 877*k7Q23NsX
    - docker push ilsaffff/ci-cd:latest
