push to github:
  stage: build
  image:
    name: alpine/git:latest
    entrypoint: [""]
  only:
    - main
    - release
  script:
    - git clone --mirror https://Ilsaf:glpat-m1yiTFj7wsyy--GobGXW@appliedmath.gitlab.yandexcloud.net/computemath/cicd_python_cnn.git
    - cd cicd_python_cnn.git
    - git remote set-url --push origin https://Ilsaffff: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@github.com/Ilsaffff/test-release-.git
    - git fetch --all
    # Извлекаем название последнего коммита
    - last_commit_message=$(git log -1 --pretty=%B)
    # Создаем временную ветку для выполнения squash
    - git checkout -b squash_branch
    # Выполняем squash всех коммитов в один
    - git reset $(git rev-list --max-parents=0 HEAD)
    - git add -A
    - git commit -m "$last_commit_message"
    # Пушим изменения в GitHub ветку master
    - git push --force origin HEAD:refs/heads/master



code quality:
  stage: build
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run black --check .
    - poetry run isort --check-only .
    - poetry run mypy --ignore-missing-imports --exclude venv .
    - poetry run radon cc --ignore venv,tests .

test execution:
  stage: test
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run pytest --cov

build and publish to docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ilsaffff/ci-cd:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push ilsaffff/ci-cd:latest


