variables:
  GITLAB_REPO_URL: "https://appliedmath.gitlab.yandexcloud.net/computemath/cicd_python_cnn.git"
  GITHUB_REPO_URL: "https://github.com/Ilsaffff/test-ci-cd.git"

download_repo:
  stage: build
  script:
    - git clone $GITLAB_REPO_URL
    - cd ci-cd

upload_repo:
  stage: build
  script:
    - git remote set-url origin $GITHUB_REPO_URL
    - git push origin --all

code quality:
  stage: build
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run black --check .
    - poetry run isort --check-only .
    - poetry run mypy --ignore-missing-imports --exclude venv .
    - poetry run radon cc --ignore venv,tests .

test execution:
  stage: test
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run pytest --cov

build and publish to docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ilsaffff/ci-cd:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push ilsaffff/ci-cd:latest


