image: python:3.10

#before_script:
#  - pip install -r requirements.txt
#
#installing-packets:
#  stage: build
#  script:

formatting:
  stage: build
  script:
    - pip install -r requirements.txt
    - black .
    - mypy --ignore-missing-imports --exclude venv .
    - isort .
    - radon cc --ignore venv,tests .

#cyclomatic-complexity:
#  stage: build
#  script:
#    - radon cc --ignore venv,tests .

testing:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest
