push to github:
  stage: build
  image:
    name: alpine/git:latest
    entrypoint: [""]
  only:
    - main
    - release
  variables:
    GIT_WORK_TREE: /tmp/cicd_work_tree
  script:
    # Создаем временную директорию для рабочего дерева
    - mkdir $GIT_WORK_TREE
    # Клонируем репозиторий с указанием рабочего дерева
    - git clone --mirror https://Ilsaf:glpat-m1yiTFj7wsyy--GobGXW@appliedmath.gitlab.yandexcloud.net/computemath/cicd_python_cnn.git $GIT_WORK_TREE/cicd_python_cnn.git
    # Устанавливаем рабочий каталог для выполнения команд
    - cd $GIT_WORK_TREE/cicd_python_cnn.git
    # Устанавливаем URL для push в GitHub
    - git remote set-url --push origin https://Ilsaffff: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@github.com/Ilsaffff/test-release-.git
    - last_commit_message=$(git log -1 --pretty=%B)
    # Создаем временную ветку для выполнения squash
    - git checkout -b squash_branch $(git rev-list --max-parents=0 HEAD)
    # Выполняем squash всех коммитов в один
    - git reset $(git rev-list --max-parents=0 HEAD) --soft
    - git commit -m "$last_commit_message"
    # Пушим изменения в GitHub в ветку master
    - git push --force origin squash_branch:refs/heads/master
  # Очищаем временную директорию после выполнения задачи
  after_script:
    - rm -rf $GIT_WORK_TREE



code quality:
  stage: build
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run black --check .
    - poetry run isort --check-only .
    - poetry run mypy --ignore-missing-imports --exclude venv .
    - poetry run radon cc --ignore venv,tests .

test execution:
  stage: test
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run pytest --cov

build and publish to docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ilsaffff/ci-cd:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push ilsaffff/ci-cd:latest


