push to github:
  stage: build
  image:
    name: alpine/git:latest
    entrypoint: [""]
  only:
    - main
    - release
  script:
    - git clone --mirror https://Ilsaf:glpat-m1yiTFj7wsyy--GobGXW@appliedmath.gitlab.yandexcloud.net/computemath/cicd_python_cnn.git
    - cd cicd_python_cnn.git
    - git remote set-url --push origin https://Ilsaffff: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@github.com/Ilsaffff/test-release-.git
    - git push --mirror
    - git fetch --all
    # Find the commit hash you want to squash and push
    - read -p "Enter the commit hash to squash and push to master:" commit_hash
    # Create a new branch with the commit you want to squash
    - git checkout -b squash_branch $commit_hash
    # Amend the commit to allow editing the commit message
    - git commit --amend
    # Squash all commits into a single commit
    - git rebase -i HEAD~$(git rev-list --count $commit_hash..HEAD)
    # Push the squashed commit to GitHub master
    - git push --force origin HEAD:refs/heads/master



code quality:
  stage: build
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run black --check .
    - poetry run isort --check-only .
    - poetry run mypy --ignore-missing-imports --exclude venv .
    - poetry run radon cc --ignore venv,tests .

test execution:
  stage: test
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run pytest --cov

build and publish to docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ilsaffff/ci-cd:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push ilsaffff/ci-cd:latest


